services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: lib-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    container_name: lib-app
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_DRIVER: ${DATASOURCE_DRIVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
      - flyway
