services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: lib-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} --quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    container_name: lib-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_DRIVER: ${DATASOURCE_DRIVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"
      - "8443:8443"
