services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: lib-db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} --quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    restart: unless-stopped
    container_name: lib-redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
