spring:

  #Application settings
  application:
    name: LibraryWithSecurity

  # Database settings
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # Flyway settings
  flyway:
    baseline-version: '0'
    baseline-on-migrate: true
    sql-migration-prefix: V
    locations: classpath:migration

  # Hibernate settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null

  #Redis settings
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
    redis:
      time-to-live: 600000

  #RabbitMQ
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    exchange: ${RABBIT_EXCHANGE:notification.exchange}
    library:
      queue: ${RABBIT_LIBRARY_MAIL_QUEUE:library.mail.queue}
      routingKey: ${RABBIT_LIBRARY_MAIL_RK:library.notification}

# OpenApi settings
springdoc:
  api-docs:
    enabled: true
    path: /lib-openapi-docs

#Client settings
top-pdf-converter:
  base-url: ${CLIENT_BASE_URL}/${CLIENT_BASE_PATH}

server:
  port: ${LIBRARY_SERVICE_PORT:8085}