spring:
  application:
    name: LibraryWithSecurity

  # Database settings
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # Hibernate settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    validate-on-migrate: true


  mvc:
    hiddenmethod:
      filter:
        enabled: true
